#!/bin/sh

cd rtppythonmeetup

case $1 in
    dev)
        pipenv install --dev
        exec pipenv run python manage.py runserver 0.0.0.0:8001
        ;;
    prod)
        exec pipenv run gunicorn rtppythonmeetup.wsgi:application --bind 0.0.0.0:8001 --workers 3
        ;;
    test)
        pipenv install --dev
        exec pipenv run python manage.py test
        ;;
    *)
        echo "Usage: $0 <dev|prod|test>"
        ;;
esac
